name: Create Release for the Repository

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    release:
        uses: ./.github/workflows/semantic-release.yml
        with:
            dry-run: ${{ github.event_name == 'pull_request' }}
        secrets:
            PAT: ${{ secrets.PAT }}
